# Generated by Django 5.2.3 on 2025-06-20 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('internal', 'داخلي فقط'), ('google', 'Google Ads'), ('facebook', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok Ads'), ('combined', 'متكامل')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('paused', 'متوقف'), ('completed', 'مكتمل')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
