# Generated by Django 5.2.3 on 2025-06-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب')], default='email', max_length=20, verbose_name='طريقة الإرسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='محتوى الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
    ]
